### ISSUE TITLE
Autorbild in Datenbank einfügen

### ISSUE THREAD

**Issue by xSebbiN** [Maxi-G/WebAnwendungen#13]

**Comment by cr4kn4x** [comment]
In der Tabelle Buch fehlt noch das Attribut zur "Kurzbeschreibung".

**Comment by cr4kn4x** [comment]
ISBN sollte besser als String gespeichert werden und nicht als Zahl. 
Eventuell auch autoinkrement für die Tabellen... Daten einfügen ist sehr aufwändig

**Comment by cr4kn4x** [comment]
Datenbank Trigger für Pubilkationen erstellen. Wenn Insert in table "BUCH" dann Publikationen in der table "Autor" um 1 erhöhen.

**Comment by xSebbiN** [comment]
Habe gerade die Tabelle Buch neu erzeugt mit Autoinkrement, Kurzbeschreibung und der ISBN als text. Daten sind wie zuvor. Habe aber natürlich noch Beispieldaten für die Kurzbeschreibung hinzugefügt

**Comment by xSebbiN** [comment]
Trigger wurde erstellt und mit neuem Eintrag getestet. Sollte soweit funktionieren.
