### ISSUE TITLE
Datenbankfehler bei Gesamtbewertungen

### ISSUE THREAD

**Issue by xSebbiN** [Maxi-G/WebAnwendungen#6]
![image](https://user-images.githubusercontent.com/60928445/116539245-dc7d2480-a8e8-11eb-91e7-216ce51eb986.png)

Datenbank kann keinen Eintrag aufnehmen, wenn gegebene Gesamtbewertung bereits vorhanden ist.

**Comment by cr4kn4x** [comment]
![image](https://user-images.githubusercontent.com/81361445/116652409-6b3f7f00-a985-11eb-9624-74cfb7db191d.png)

Sieht so aus wie wenn es an dieser Zeile im SQL Skript liegt.

**Comment by cr4kn4x** [comment]
![image](https://user-images.githubusercontent.com/81361445/116654090-c1fa8800-a988-11eb-9c6a-b75e9f9fe6f0.png)


Hab die Tabelle "Bewertungen" gelöscht und neu erstellt.

**Comment by xSebbiN** [comment]
nice well done
